export const COURSE_TOGGLE_TO_BASKET = 'COURSE_TOGGLE_TO_BASKET';
export const ADD_GECOURSE_TO_BASKET = 'ADD_GECOURSE_TO_BASKET';
export const ADD_B2BCOURSE_TO_BASKET = 'ADD_B2BCOURSE_TO_BASKET';
export const ADD_ABROADCOURSE_TO_BASKET = 'ADD_ABROADCOURSE_TO_BASKET';
export const REMOVE_COURSE_FROM_BASKET = 'REMOVE_COURSE_FROM_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const OREDR_SUBMIT_START = 'OREDR_SUBMIT_START';
export const OREDR_SUBMIT_SUCCESS = 'OREDR_SUBMIT_SUCCESS';
export const OREDR_SUBMIT_FAIL = 'OREDR_SUBMIT_FAIL';

export const LOGOUT = 'LOGOUT';

export const ORDERS_FETCH_START = 'ORDERS_FETCH_START';
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS';
export const ORDERS_FETCH_FAIL = 'ORDERS_FETCH_FAIL';


export const POP_UP_MODAL_ACTIVATED = 'POP_UP_MODAL_ACTIVATED';
export const POP_UP_MODAL_DISACTIVATED = 'POP_UP_MODAL_DISACTIVATED';
