export const COURSE_TOGGLE_TO_BASKET = 'COURSE_TOGGLE_TO_BASKET';
export const ADD_GECOURSE_TO_BASKET = 'ADD_GECOURSE_TO_BASKET';
export const ADD_B2BCOURSE_TO_BASKET = 'ADD_B2BCOURSE_TO_BASKET';
export const ADD_ABROADCOURSE_TO_BASKET = 'ADD_ABROADCOURSE_TO_BASKET';
export const REMOVE_COURSE_FROM_BASKET = 'REMOVE_COURSE_FROM_BASKET';
export const CLEAR_BASKET_AFTER_FORM_SENT = 'CLEAR_BASKET_AFTER_FORM_SENT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const OREDR_SUBMIT_START = 'OREDR_SUBMIT_START';
export const OREDR_SUBMIT_SUCCESS = 'OREDR_SUBMIT_SUCCESS';
export const OREDR_SUBMIT_FAIL = 'OREDR_SUBMIT_FAIL';
